stages:
  - androidbuild
  - androidtest

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - mblal-tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/AndroidExample/gradlew
  script:
    - cd Frontend/AndroidExample
    - ./gradlew build
  only:
    refs:
      - mblal_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - mblal-tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/AndroidExample/gradlew
  script:
    - cd Frontend/AndroidExample
    - ./gradlew test
  only:
    refs:
      - mblal_CICD
    changes:
      - Frontend/**/*