## H2 in-memory database setup
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## auto-create tables
#spring.jpa.hibernate.ddl-auto=update
#
## enable H2 web console (http://localhost:8080/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

## MySQL local setup (Phase 2)
#spring.datasource.url=jdbc:mysql://localhost:3306/questbuddy?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=secoms3190
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

## Remote MariaDB (via SSH tunnel) (Phase 3)
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/questbuddy?useSSL=false&serverTimezone=UTC
spring.datasource.username=questbuddy_user
spring.datasource.password=team_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
