# Remote MariaDB running on coms-3090-026.class.las.iastate.edu
spring.datasource.url=jdbc:mysql://coms-3090-026.class.las.iastate.edu:3306/questbuddy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Chicago&useLegacyDatetimeCode=false
spring.datasource.username=questbuddy_user
spring.datasource.password=team_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*

stripe:
secret-key: ${STRIPE_SECRET_KEY}
publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_dummy}
webhook-secret: ${STRIPE_WEBHOOK_SECRET}