package com.questbuddy.notification;

public enum NotificationType {
    INVITE, APPROVAL, TASK, REMINDER,
    FRIEND_REQUEST, FRIEND_ACCEPTED, FRIEND_REJECTED,
    EVENT_CREATED, EVENT_UPDATED, EVENT_CANCELLED,
    TASK_ASSIGNED, TASK_COMPLETED,

    TRIP_INVITE,
    TRIP_JOIN_REQUEST,
    TRIP_INVITE_ACCEPTED,
    TRIP_INVITE_DECLINED,
    TRIP_REQUEST_APPROVED,
    TRIP_REQUEST_DENIED
}